before:
  hooks:
    - go mod download
builds:
  - binary: kubectl-power-forward
    main: ./cmd/kubectl-power-forward
    ldflags:
      - "-s -w -extldflags '-static'"
      - "-X main.version={{ .Version }}"
      - "-X main.commit={{ .Commit }}"
      - "-X main.date={{ .CommitDate }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  draft: true
  replace_existing_draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^build'
      - '^chore'
  groups:
    - title: Breaking change
      regexp: '^.*([[:word:]]+)(\([[:word:]]+\))??!:.+$'
      order: 0
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug fixes'
      regexp: '^.*fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other'
      order: 999
