baseURL = "https://mikel-jason.github.io/kubectl-power-forward/"
title = "kubectl power-forward"

contentDir = "content"

enableRobotsTXT = true
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango" # https://xyproto.github.io/splash/docs/all.html

[outputs]
section = ["HTML", "print", "RSS"]

[params]
github_repo = "https://github.com/mikel-jason/kubectl-power-forward"
github_subdir = "website"
github_branch= "main"

offlineSearch = false
prism_syntax_highlighting = false

[params.copyright]
  authors = ""
  from_year = 2024

# User interface configuration
[params.ui]
breadcrumb_disable = false
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = false
sidebar_search_disable = false

[params.ui.readingtime]
enable = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.123.8"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
